-- CLIENTE definição

-- Drop table

-- DROP TABLE CLIENTE;

CREATE TABLE CLIENTE (
	ID_CLIENTE BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	CODIGO BIGINT DEFAULT '0' NOT NULL,
	NOME VARCHAR(150) NOT NULL,
	ENDERECO VARCHAR(150),
	CONTATO VARCHAR(150),
	OBS BLOB SUB_TYPE TEXT,
	PERMITIR_SALDO_NEGATIVO BOOLEAN DEFAULT true NOT NULL,
	ATIVO BOOLEAN DEFAULT true NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
);


-- CONFIGURACOES definição

-- Drop table

-- DROP TABLE CONFIGURACOES;

CREATE TABLE CONFIGURACOES (
	ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	NOME VARCHAR(150) NOT NULL,
	TIPO_CAMPO VARCHAR(10) NOT NULL,
	T_BIGINT BIGINT,
	T_BOOLEAN BOOLEAN,
	T_VARCHAR VARCHAR(255),
	T_NUMERIC NUMERIC(15,2),
	T_TIMESTAMP TIMESTAMP,
	T_BLOB BLOB SUB_TYPE BINARY,
	CONSTRAINT PK_CONFIGURACOES PRIMARY KEY (ID)
);


-- IBE$LOG_BLOB_FIELDS definição

-- Drop table

-- DROP TABLE IBE$LOG_BLOB_FIELDS;

CREATE TABLE IBE$LOG_BLOB_FIELDS (
	LOG_TABLES_ID NUMERIC(18,0) NOT NULL,
	FIELD_NAME VARCHAR(67) NOT NULL,
	OLD_CHAR_VALUE VARCHAR(8000),
	NEW_CHAR_VALUE VARCHAR(8000),
	OLD_BLOB_VALUE BLOB SUB_TYPE BINARY,
	NEW_BLOB_VALUE BLOB SUB_TYPE BINARY
);
CREATE INDEX IBE$LOG_BLOB_FIELDS_IDX1 ON IBE$LOG_BLOB_FIELDS (LOG_TABLES_ID);


-- IBE$LOG_FIELDS definição

-- Drop table

-- DROP TABLE IBE$LOG_FIELDS;

CREATE TABLE IBE$LOG_FIELDS (
	LOG_TABLES_ID NUMERIC(18,0) NOT NULL,
	FIELD_NAME VARCHAR(67) NOT NULL,
	OLD_VALUE VARCHAR(255),
	NEW_VALUE VARCHAR(255)
);
CREATE INDEX IBE$LOG_FIELDS_IDX1 ON IBE$LOG_FIELDS (LOG_TABLES_ID);


-- IBE$LOG_KEYS definição

-- Drop table

-- DROP TABLE IBE$LOG_KEYS;

CREATE TABLE IBE$LOG_KEYS (
	LOG_TABLES_ID NUMERIC(18,0) NOT NULL,
	KEY_FIELD VARCHAR(67) NOT NULL,
	KEY_VALUE VARCHAR(255)
);
CREATE INDEX IBE$LOG_KEYS_IDX1 ON IBE$LOG_KEYS (LOG_TABLES_ID);


-- IBE$LOG_TABLES definição

-- Drop table

-- DROP TABLE IBE$LOG_TABLES;

CREATE TABLE IBE$LOG_TABLES (
	ID NUMERIC(18,0) NOT NULL,
	TABLE_NAME VARCHAR(67) NOT NULL,
	OPERATION VARCHAR(1) NOT NULL,
	DATE_TIME TIMESTAMP NOT NULL,
	USER_NAME VARCHAR(67) NOT NULL,
	CONSTRAINT INTEG_69 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY4 ON IBE$LOG_TABLES (ID);


-- MESA definição

-- Drop table

-- DROP TABLE MESA;

CREATE TABLE MESA (
	ID_MESA BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	CODIGO BIGINT DEFAULT '0' NOT NULL,
	DESCRICAO VARCHAR(150) NOT NULL,
	"LEFT" INTEGER,
	TOP INTEGER,
	TAMANHO INTEGER,
	IMAGEM BLOB SUB_TYPE BINARY,
	ATIVA BOOLEAN DEFAULT true NOT NULL,
	CONSTRAINT PK_MESA PRIMARY KEY (ID_MESA)
);


-- TEMPORADAS definição

-- Drop table

-- DROP TABLE TEMPORADAS;

CREATE TABLE TEMPORADAS (
	ID_TEMPORADAS BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	COD_TEMP SMALLINT NOT NULL,
	PERIODO_INICIAL DATE DEFAULT current_date NOT NULL,
	PERIODO_FINAL DATE,
	DESCRICAO VARCHAR(150) NOT NULL,
	ATIVO BOOLEAN DEFAULT false NOT NULL,
	CONSTRAINT PK_TEMPORADAS PRIMARY KEY (ID_TEMPORADAS)
);


-- TIPO_PAGAMENTO definição

-- Drop table

-- DROP TABLE TIPO_PAGAMENTO;

CREATE TABLE TIPO_PAGAMENTO (
	ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	DESCRICAO VARCHAR(150) NOT NULL,
	ATIVO BOOLEAN DEFAULT TRUE NOT NULL,
	CONSTRAINT PK_TIPO_PAGAMENTO PRIMARY KEY (ID)
);


-- USUARIOS definição

-- Drop table

-- DROP TABLE USUARIOS;

CREATE TABLE USUARIOS (
	ID BIGINT DEFAULT '0' NOT NULL,
	NOME VARCHAR(150) NOT NULL,
	PWD VARCHAR(255) NOT NULL,
	HABILITADO BOOLEAN DEFAULT true NOT NULL,
	CONSTRAINT PK_USUARIOS PRIMARY KEY (ID),
	CONSTRAINT UNQ1_USUARIOS UNIQUE (NOME)
);


-- DEPENDENTES definição

-- Drop table

-- DROP TABLE DEPENDENTES;

CREATE TABLE DEPENDENTES (
	ID_DEPENDENTES BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	CODIGO BIGINT DEFAULT '0' NOT NULL,
	NOME VARCHAR(150) NOT NULL,
	FK_CLIENTE BIGINT NOT NULL,
	FONE VARCHAR(150),
	OBS BLOB SUB_TYPE TEXT,
	PERMITIR_RETIRAR BOOLEAN DEFAULT true NOT NULL,
	CONSTRAINT PK_DEPENDENTES PRIMARY KEY (ID_DEPENDENTES),
	CONSTRAINT FK_DEPENDENTES_CLIENTES FOREIGN KEY (FK_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX FK_DEPENDENTES_CLIENTES ON DEPENDENTES (FK_CLIENTE);


-- ENTRADA_SAIDA definição

-- Drop table

-- DROP TABLE ENTRADA_SAIDA;

CREATE TABLE ENTRADA_SAIDA (
	ID BIGINT DEFAULT '0' NOT NULL,
	DESCRICAO VARCHAR(150) NOT NULL,
	VALOR NUMERIC(15,2) NOT NULL,
	TIPO INTEGER NOT NULL,
	DATA_HORA TIMESTAMP DEFAULT current_timeStamp,
	EXCLUIDO BOOLEAN DEFAULT false NOT NULL,
	USER_DEL VARCHAR(150),
	DATA_HORA_EXC TIMESTAMP,
	FK_TEMPORADA BIGINT NOT NULL,
	CONSTRAINT PK_ENTRADA_SAIDA PRIMARY KEY (ID),
	CONSTRAINT FK_ENTRADA_SAIDA_1 FOREIGN KEY (FK_TEMPORADA) REFERENCES TEMPORADAS(ID_TEMPORADAS) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX FK_ENTRADA_SAIDA_1 ON ENTRADA_SAIDA (FK_TEMPORADA);


-- PEDIDO definição

-- Drop table

-- DROP TABLE PEDIDO;

CREATE TABLE PEDIDO (
	ID_PEDIDO BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	FK_TEMPORADA BIGINT NOT NULL,
	DTHR_ABERTURA TIMESTAMP DEFAULT current_timestamp NOT NULL,
	DTHR_FEXAMENTO TIMESTAMP,
	FK_MESA BIGINT,
	FK_DEPENDENTE BIGINT,
	DESCONTO BOOLEAN DEFAULT true NOT NULL,
	VALOR_DESCONTO NUMERIC(15,2) DEFAULT 0 NOT NULL,
	PAGO BOOLEAN DEFAULT False NOT NULL,
	FK_CLIENTE BIGINT,
	NOME_DEPENDENTE VARCHAR(150),
	ANOTAR BOOLEAN DEFAULT false NOT NULL,
	TP_PAGAMENTO INTEGER,
	CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO),
	CONSTRAINT FK_PEDIDO_1 FOREIGN KEY (TP_PAGAMENTO) REFERENCES TIPO_PAGAMENTO(ID) ON DELETE SET NULL ON UPDATE SET NULL,
	CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (FK_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_PEDIDO_DEPENDENTE FOREIGN KEY (FK_DEPENDENTE) REFERENCES DEPENDENTES(ID_DEPENDENTES) ON DELETE SET NULL ON UPDATE SET NULL,
	CONSTRAINT FK_PEDIDO_MESA FOREIGN KEY (FK_MESA) REFERENCES MESA(ID_MESA) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_PEDIDO_TEMP FOREIGN KEY (FK_TEMPORADA) REFERENCES TEMPORADAS(ID_TEMPORADAS) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX FK_PEDIDO_1 ON PEDIDO (TP_PAGAMENTO);
CREATE INDEX FK_PEDIDO_CLIENTE ON PEDIDO (FK_CLIENTE);
CREATE INDEX FK_PEDIDO_DEPENDENTE ON PEDIDO (FK_DEPENDENTE);
CREATE INDEX FK_PEDIDO_MESA ON PEDIDO (FK_MESA);
CREATE INDEX FK_PEDIDO_TEMP ON PEDIDO (FK_TEMPORADA);


-- PRODUTOS definição

-- Drop table

-- DROP TABLE PRODUTOS;

CREATE TABLE PRODUTOS (
	ID_RODUTOS BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	CODIGO BIGINT DEFAULT '0' NOT NULL,
	FK_TEMPORADA BIGINT DEFAULT '0' NOT NULL,
	NOME VARCHAR(150) NOT NULL,
	VALOR_UNI NUMERIC(15,4) NOT NULL,
	CONSTRAINT PK_PRODUTOS PRIMARY KEY (ID_RODUTOS),
	CONSTRAINT UK_NOME_TEMPORADA UNIQUE (FK_TEMPORADA,NOME),
	CONSTRAINT UK_PRODUTO_TEMPORADA UNIQUE (CODIGO,FK_TEMPORADA),
	CONSTRAINT FK_PRODUTOS_TEMPORADA FOREIGN KEY (FK_TEMPORADA) REFERENCES TEMPORADAS(ID_TEMPORADAS) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX FK_PRODUTOS_TEMPORADA ON PRODUTOS (FK_TEMPORADA);


-- CADERNETA_CLIENTE definição

-- Drop table

-- DROP TABLE CADERNETA_CLIENTE;

CREATE TABLE CADERNETA_CLIENTE (
	ID_CADERNETA BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	DTHR_LANCAMENTO TIMESTAMP DEFAULT Current_timestamp NOT NULL,
	FK_CLIENTE BIGINT NOT NULL,
	FK_DEPENDENTE BIGINT NOT NULL,
	FK_PEDIDO BIGINT,
	FK_TEMPORADA BIGINT,
	CONSTRAINT PK_CADERNETA_CLIENTE PRIMARY KEY (ID_CADERNETA),
	CONSTRAINT FK_CADERNETA_CLIENTE FOREIGN KEY (FK_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_CADERNETA_DEPENDENTE FOREIGN KEY (FK_DEPENDENTE) REFERENCES DEPENDENTES(ID_DEPENDENTES) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT FK_CADERNETA_PEDIDO FOREIGN KEY (FK_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX FK_CADERNETA_CLIENTE ON CADERNETA_CLIENTE (FK_CLIENTE);
CREATE INDEX FK_CADERNETA_DEPENDENTE ON CADERNETA_CLIENTE (FK_DEPENDENTE);
CREATE INDEX FK_CADERNETA_PEDIDO ON CADERNETA_CLIENTE (FK_PEDIDO);


-- MOV_PRODUTO definição

-- Drop table

-- DROP TABLE MOV_PRODUTO;

CREATE TABLE MOV_PRODUTO (
	ID_MOV_PRODUTO BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	FK_PEDIDO BIGINT,
	FK_PRODUTO BIGINT,
	QUANTIDADE NUMERIC(15,4) DEFAULT 1 NOT NULL,
	PAGAMENTO BOOLEAN DEFAULT false NOT NULL,
	VALOR_TOTAL NUMERIC(15,2) DEFAULT 0 NOT NULL,
	FK_CADERNETA BIGINT,
	DATA_HORA TIMESTAMP DEFAULT current_timeStamp NOT NULL,
	TIPO_PAGAMENTO INTEGER,
	EXCLUIDO BOOLEAN DEFAULT false NOT NULL,
	USER_DEL VARCHAR(150),
	DIA_MOV DATE,
	DATA_HORA_EXC TIMESTAMP,
	CONSTRAINT PK_MOV_PRODUTO PRIMARY KEY (ID_MOV_PRODUTO),
	CONSTRAINT FK_MOV_PRODUTO_1 FOREIGN KEY (TIPO_PAGAMENTO) REFERENCES TIPO_PAGAMENTO(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_MOV_PRODUTO_CADERNETA FOREIGN KEY (FK_CADERNETA) REFERENCES CADERNETA_CLIENTE(ID_CADERNETA) ON DELETE SET NULL ON UPDATE SET NULL,
	CONSTRAINT FK_PEDIDO FOREIGN KEY (FK_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_PRODUTO FOREIGN KEY (FK_PRODUTO) REFERENCES PRODUTOS(ID_RODUTOS) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX FK_MOV_PRODUTO_1 ON MOV_PRODUTO (TIPO_PAGAMENTO);
CREATE INDEX FK_MOV_PRODUTO_CADERNETA ON MOV_PRODUTO (FK_CADERNETA);
CREATE INDEX FK_PEDIDO ON MOV_PRODUTO (FK_PEDIDO);
CREATE INDEX FK_PRODUTO ON MOV_PRODUTO (FK_PRODUTO);

-- MESA_PEDIDO fonte

CREATE OR ALTER VIEW MESA_PEDIDO (ID_MESA, CODIGO, DESCRICAO, ATIVA, ID_PEDIDO, FK_TEMPORADA, DTHR_ABERTURA, DTHR_FEXAMENTO, FK_DEPENDENTE, DESCONTO, VALOR_DESCONTO, PAGO, NOME_DEPENDENTE, ANOTAR, NOME, COD_CLIENTE, ID_CLIENTE, TP_PAGAMENTO, TOTAL)
AS
select 
  m.id_mesa
  ,m.codigo
  ,m.descricao
  ,m.ativa
  ,id_pedido
  ,fk_temporada
  ,dthr_abertura
  ,dthr_fexamento
  ,fk_dependente
  ,desconto
  ,valor_desconto
  ,pago
  ,nome_dependente
  ,anotar
  ,c.nome
  ,c.codigo Cod_cliente
  ,c.id_cliente
  ,k.tp_pagamento
  ,(
    select 
      sum(/*iif(v.pagamento, (- 1), 1) **/ v.valor_total)
    from 
      mov_produto v
    where 
      v.fk_pedido = k.id_pedido
    ) Total
from 
  mesa m
  full outer join (
    select 
      p.*
    from 
      pedido p
      left join temporadas t on t.id_temporadas = p.fk_temporada
    where 
      t.ativo = true
      and p.dthr_fexamento is null
    ) k on k.fk_mesa = m.id_mesa
  left join cliente c on c.id_cliente = k.fk_cliente;


-- SALDO_CLIENTE fonte

CREATE OR ALTER VIEW SALDO_CLIENTE (ID_CADERNETA, DTHR_LANCAMENTO, FK_TEMPORADA, FK_CLIENTE, FK_DEPENDENTE, ID_MOV_PRODUTO, FKS, QUANTIDADE, PAGAMENTO, VALOR_TOTAL, SALDO, TOTAL_PEDIDO)
AS
select
  cc.id_caderneta
  , cc.dthr_lancamento
  ,	ped.fk_temporada
  , cc.fk_cliente
  , cc.fk_dependente
  , mv.id_mov_produto
  , cast(coalesce(mv.fk_produto, 'T'||mv.tipo_pagamento) as varchar(20)) fks
  , mv.quantidade
  , mv.pagamento
  , mv.valor_total
/* valor pagamento passou a ser armazenado como negativo para facilitar as coisas
  ,sum(iif(mv.pagamento,1,-1)*mv.valor_total) over (partition by pr.fk_temporada,cc.fk_cliente order by mv.id_mov_produto) Saldo
  ,sum(iif(mv.pagamento,1,-1)*mv.valor_total) over (partition by mv.fk_pedido order by mv.id_mov_produto) Total_pedido
*/
  ,sum(mv.valor_total) over (partition by ped.fk_temporada,cc.fk_cliente order by mv.id_mov_produto) Saldo
  ,sum(mv.valor_total) over (partition by mv.fk_pedido order by mv.id_mov_produto) Total_pedido

from
  caderneta_cliente cc
  join mov_produto mv on cc.id_caderneta = mv.fk_caderneta
  left join produtos pr on pr.id_rodutos = mv.fk_produto
  left join pedido ped on ped.id_pedido = mv.fk_pedido;


-- VENDAS_ACOMULADO fonte

CREATE OR ALTER VIEW VENDAS_ACOMULADO (DIA_MOV, ANTERIOR, VENDAS, PAGAMENTOS, ARECEBER, VENDAS_ACOM)
AS
select
*
from
  pr_vendas_acomulado;


CREATE OR ALTER PROCEDURE PR_FECHAR_ANOTAR (IN_PEDIDO INTEGER NOT NULL, IN_CLIENTE INTEGER NOT NULL, IN_DEPENDENTE INTEGER NOT NULL, IN_DESC_DEPENDENTE VARCHAR(150) NOT NULL)
AS
begin
   
  INSERT INTO CADERNETA_CLIENTE
    (DTHR_LANCAMENTO, FK_CLIENTE, FK_DEPENDENTE, FK_PEDIDO)
    VALUES(Current_timestamp, :in_cliente, :in_dependente, :in_pedido);


  UPDATE PEDIDO p
  SET
    p.DTHR_FEXAMENTO=current_timestamp,
    p.ANOTAR=true,
    p.TP_PAGAMENTO=1,
    p.fk_dependente=:in_dependente,
    p.fk_cliente= :in_cliente,
    p.nome_dependente = :in_desc_dependente
  WHERE
    ID_PEDIDO=:in_pedido;
end;

CREATE OR ALTER PROCEDURE PR_FECHAR_PAGAR (IN_PEDIDO INTEGER NOT NULL, IN_TP_PAGAMENTO INTEGER NOT NULL, IN_VALOR DECIMAL(15,2) NOT NULL)
AS
begin

  INSERT INTO MOV_PRODUTO
  (ID_MOV_PRODUTO,FK_PEDIDO,  QUANTIDADE, PAGAMENTO, VALOR_TOTAL, DATA_HORA, TIPO_PAGAMENTO )
  VALUES(GEN_ID(gen_mov_produto,1),:in_pedido,  1, TRUE, (:in_valor*-1),  current_timeStamp, :in_tp_pagamento);

  UPDATE PEDIDO
  SET
    DTHR_FEXAMENTO=current_timestamp,
    ANOTAR=false,
    TP_PAGAMENTO=:in_tp_pagamento
  WHERE
    ID_PEDIDO=:in_pedido;
end;

CREATE OR ALTER PROCEDURE PR_LANCAR_CADERNETA_DIRETO (IN_DTHR_LANCAMENTO TIMESTAMP, IN_CLIENTE INTEGER, IN_DEPENDENTE INTEGER, IN_DESC_DEPENDENTE VARCHAR(150), IN_TEMPORADA INTEGER, IN_PRODUTO INTEGER, IN_QUANT NUMERIC(15,4), IN_VALOR_TOTAL NUMERIC(15,4))
AS
declare variable id_pedido type of column pedido.id_pedido;
BEGIN
INSERT
  INTO
    PEDIDO (
      FK_TEMPORADA,
      DTHR_ABERTURA,
      DTHR_FEXAMENTO,
      FK_MESA,
      FK_DEPENDENTE,
      FK_CLIENTE,
      NOME_DEPENDENTE,
      ANOTAR,
      TP_PAGAMENTO
    )
  VALUES
    (
      :in_temporada,
      :IN_DTHR_LANCAMENTO,
      :IN_DTHR_LANCAMENTO,
      null,
      :IN_DEPENDENTE,
      :IN_CLIENTE,
      :IN_DESC_DEPENDENTE,
      true,
      1
    )
  RETURNING
    ID_PEDIDO
  into  
    :id_pedido
  ;

  INSERT
  INTO
    MOV_PRODUTO (
      id_mov_produto,
      FK_PEDIDO,
      FK_PRODUTO,
      QUANTIDADE,
      PAGAMENTO,
      VALOR_TOTAL,
      FK_CADERNETA,
      DATA_HORA
    )
  VALUES(
    gen_id( gen_mov_produto,1),
    :id_pedido,
    :IN_PRODUTO,
    :IN_QUANT,
    FALSE,
    :IN_VALOR_TOTAL,
    null,
    :IN_DTHR_LANCAMENTO
  );


INSERT
  INTO
    CADERNETA_CLIENTE (
      DTHR_LANCAMENTO,
      FK_CLIENTE,
      FK_DEPENDENTE,
      FK_PEDIDO,
      FK_TEMPORADA
    )
  VALUES(
    :IN_DTHR_LANCAMENTO,
    :in_cliente,
    :in_dependente,
    :id_pedido,
    :in_temporada
  );
END;

CREATE OR ALTER PROCEDURE PR_PAGAR_CADERNETA_DIRETO (IN_DTHR_LANCAMENTO TIMESTAMP, IN_CLIENTE INTEGER, IN_TP_PAGAMENTO INTEGER NOT NULL, IN_TEMPORADA INTEGER, IN_VALOR_TOTAL NUMERIC(15,4))
AS
declare variable ID_CADERNETA type of column CADERNETA_CLIENTE.ID_CADERNETA;
BEGIN


  insert into caderneta_cliente (
    dthr_lancamento,
    fk_cliente,
    fk_dependente,
    fk_temporada)
  values (
    :in_dthr_lancamento,
    :in_cliente,
    (select first 1
       d.id_dependentes
     from
       dependentes d
     where
         d.fk_cliente = :in_cliente),
    :in_temporada)
  returning
    id_caderneta
  into
    :id_caderneta;
  

  INSERT
  INTO
    MOV_PRODUTO (
      id_mov_produto,
      FK_CADERNETA,      
      QUANTIDADE,
      PAGAMENTO,
      VALOR_TOTAL,     
      DATA_HORA,
      TIPO_PAGAMENTO
    )
  VALUES(
    gen_id( gen_mov_produto,1),
    :ID_CADERNETA,    
    1,
    true,
    (:IN_VALOR_TOTAL*-1),
    :IN_DTHR_LANCAMENTO,
    :IN_TP_PAGAMENTO
  );


END;

CREATE OR ALTER PROCEDURE PR_VENDAS_ACOMULADO RETURNS (
	DIA_MOV DATE,
	ANTERIOR NUMERIC(18,2),
	VENDAS NUMERIC(18,2),
	PAGAMENTOS NUMERIC(18,2),
	ARECEBER NUMERIC(18,2),
	VENDAS_ACOM NUMERIC(18,2)
)
AS
declare DESCONTO NUMERIC(18,2);
  declare DESC_ACOM NUMERIC(18,2);
  declare VENDA_DIA NUMERIC(18,2);
begin
  :ANTERIOR = 0;
  :desc_acom = 0;
  :vendas_acom = 0;
  :areceber= 0 ;
  FOR select distinct
      mv.dia_mov,
      sum(iif(mv.pagamento, 0, mv.valor_total)) vendas,
      sum(iif(mv.pagamento and mv.tipo_pagamento <> 5, mv.valor_total * -1, 0)) pagamentos,
      sum(iif(mv.pagamento and mv.tipo_pagamento = 5, mv.valor_total * -1, 0)) descontos
    from
      mov_produto mv
    where
        not mv.excluido and
        mv.dia_mov between
              (select
                 t.periodo_inicial
               from
                 temporadas t
               where
                   t.ativo)
               and (select
                       coalesce(t.periodo_final, current_date)
                     from
                       temporadas t
                     where
                         t.ativo)
          group by
              dia_mov
          order by
              mv.dia_mov
  into
    :dia_mov,
    :venda_dia,
    :pagamentos,
    :desconto
  do
  BEGIN
    :vendas = :venda_dia-:desconto;
    :areceber = :areceber +:vendas-:pagamentos;
    :desc_acom = :desc_acom + :desconto;
    :vendas_acom = :vendas_acom + :vendas;
    suspend;
    :anterior=:vendas_acom;
  END
end;


CREATE TRIGGER TR_TEMPOR_ATIVO FOR TEMPORADAS AFTER INSERT OR UPDATE
AS
begin
  if (new.ativo) then
  begin
    update temporadas t
    set
      t.ativo = false
    where
      T.ativo
      and t.id_temporadas <> new.id_temporadas;
  end
end;

CREATE TRIGGER TR_TEMPOR_DATA_FIM FOR TEMPORADAS AFTER INSERT
AS
begin
  update temporadas t
  set t.periodo_final = dateadd(day, -1, cast(new.periodo_inicial as date))
  where t.periodo_final is null and
        t.periodo_inicial < dateadd(day, -1, cast(new.periodo_inicial as date)) ;
end;

CREATE TRIGGER CADERNETA_CLIENTE_AI0 FOR CADERNETA_CLIENTE AFTER INSERT
AS
begin
  if (new.fk_pedido is not null) then
  update mov_produto m
  set
    m.fk_caderneta = new.id_caderneta
  where
    m.fk_pedido = new.fk_pedido;

end;

CREATE TRIGGER CADERNETA_CLIENTE_BIU0 FOR CADERNETA_CLIENTE BEFORE INSERT OR UPDATE
AS
  declare variable id_temp type of column temporadas.id_temporadas;
begin
  if (new.fk_temporada is null) then
  begin
    if (new.fk_pedido is not null) then
    begin
      select
        p.fk_temporada
      from
        pedido p
      where
        p.id_pedido = new.fk_pedido
      into
        :id_temp;
    end
    else begin
      select
        t.id_temporadas
      from
        temporadas t
      where
        t.ativo
      into
        :id_temp ;
    end
    new.fk_temporada = :id_temp;
  end
end;

CREATE TRIGGER MESA_PEDIDO_BI0 FOR MESA_PEDIDO BEFORE INSERT OR UPDATE
AS
begin
  update or insert into pedido
    (
      id_pedido
      , fk_temporada
      , dthr_abertura
      , dthr_fexamento
      , fk_mesa
      , fk_dependente
      , fk_cliente
      , nome_dependente
      , anotar
      , tp_pagamento
    )
  values
    (
      new.id_pedido
      , new.fk_temporada
      ,new.dthr_abertura
      , new.dthr_fexamento
      , new.id_mesa
      , new.fk_dependente
      , new.id_cliente
      , new.nome_dependente
      , new.anotar
      , new.tp_pagamento
    )
  matching (id_pedido);

end;

CREATE TRIGGER USUARIOS_BI FOR USUARIOS BEFORE INSERT
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_usuarios_id,1);
end;

CREATE TRIGGER MOV_PRODUTO_BI0 FOR MOV_PRODUTO BEFORE INSERT
AS
begin
  if (new.id_mov_produto is null) then
    new.id_mov_produto = gen_id(gen_mov_produto,1);
end;

CREATE TRIGGER ENTRADA_SAIDA_BI FOR ENTRADA_SAIDA BEFORE INSERT
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_ENTRADA_SAIDA_id,1);
end;